//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectContainerPartPlacement
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int ProjectParentContainerPartId { get; set; }
        public Nullable<int> ProjectChildContainerPartId { get; set; }
        public Nullable<int> ProjectChildSimplePartId { get; set; }
        public int Quantity { get; set; }
    }
}
