//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public bool IsString { get; set; }
        public bool IsInteger { get; set; }
        public bool IsDouble { get; set; }
        public bool IsBoolean { get; set; }
        public string Name { get; set; }
    }
}
